name: projectBackEndTest

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:

    - uses: getong/redis-action@v1
      with:
          redis version: 'latest'
          host port: 6379
          container port: 6379
          redis password: 'test'
    - uses: actions/checkout@v2 
    - name: Set up JDK 21 
      uses: actions/setup-java@v3
      with:
        java-version: 21 
        distribution: 'temurin' 
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Test with Gradle
      run: ./gradlew clean test
